### ISSUE TITLE
Traducció amb Markdown

### ISSUE THREAD

**Issue by sasogu** [jcarloslopez/atom-spanish-valencian-translator#1]
Hola, moltíssimes gràcies per compartir aquest plugin, he observat que en traduir documents fets en markdown quan es troba el símbol `**` al principi d'un text en negreta el canvia a `*` No sé si té solució des del plugin o és cosa de l'API d'Apertium. 

Salut

**Comment by jcarloslopez** [comment]
Hola, m'alegre que et siga útil el paquet.

Observant el que comentes he trobat que és un problema del propi Apertium. Si té desactivada l'opció de "Mark unknown word" es veu que elimina l'asterisc del principi del text com pots comprovar amb aquest exemple: https://www.apertium.org/index.spa.html?dir=spa-cat_valencia&q=*Texto%20de%20prueba*#translation.

Per a solucionar aquest problema, fins que l'arregle Apertium, selecciona l'opció de "Mark unknown words" en la configuració del paquet en Atom.

Vaig a pujar una actualització perquè estiga activada per defecte després d'instal·lar el paquet.

**Comment by sasogu** [comment]
Genial, és molt útil per a mi!! Gràcies de nou.
